### ISSUE TITLE
Moving to Open Radar org?

### ISSUE THREAD

**Issue by mgrover1** [MeteoSwiss/ERAD-Open_Source-Radar-2022#2]
Hi ya'll - since all the previous ERAD tutorial content is over in the [open radar organization](https://github.com/openradar), would it make sense to transition this repo over there? I wasn't aware a repo had been created under Meteoswiss, and already created one under Open Radar, so I figured we could merge the two?

Perhaps setting up a time to chat about infrastructure plans/content updates would be good?

**Comment by kmuehlbauer** [comment]
I'm open for having a chat about the next steps.

**Comment by jfigui** [comment]
Hi, I also think that this repo belongs to open radar. There are two months left before the conference so I think it is time to be more concrete and meet again. By the way, Slack is not allow in my organization. I don't know if I missed something.

**Comment by kmuehlbauer** [comment]
@jfigui Yes, we should meet before July 16th. I'll not be able to connect again before early August. Veli is currently on paternal leave and will also be available in August again earliest.

There wasn't that much traffic on Slack the last weeks. Which chat system would you be able to use, @jfigui? Maybe it would be a good idea to find a time range (2-3 times a week) where we can connect to some chat/video-call system. It's much easier then to interact.

**Comment by wolfidan** [comment]
@kmuehlbauer @jfigui , would you like that I organize a Microsoft Teams meeting as last time, or rather that we agree to meet on regular basis on a chat. For that purpose would the github discussions on https://github.com/openradar/erad2022/discussions be suitable?

**Comment by kmuehlbauer** [comment]
@wolfidan, @jfigui I've created a new team below openradar, where I've invited you via github. This way we can chat via github team-discussions in a more private way.

**Comment by jfigui** [comment]
OK,
I think we can use github discussions for day to day business but it would not be a bad thing if we have a quick coordination meeting to see where we are

**Comment by kmuehlbauer** [comment]
@jfigui Yes, that would indeed be worth it.

**Comment by kmuehlbauer** [comment]
Github erad team discussions: https://github.com/orgs/openradar/teams/erad2022-team/discussions

**Comment by wolfidan** [comment]
Ok I'll send a doodle for a meeting later today

**Comment by kmuehlbauer** [comment]
Done
